//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид работы.
    /// </summary>
    // *** Start programmer edit section *** (ВидРаботы CustomAttributes)

    // *** End programmer edit section *** (ВидРаботы CustomAttributes)
    [AutoAltered()]
    [Caption("Вид работы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВидРаботыE", new string[] {
            "Название as \'Название\'"})]
    [View("ВидРаботыL", new string[] {
            "Название as \'Название\'"})]
    public class ВидРаботы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (ВидРаботы CustomMembers)

        // *** End programmer edit section *** (ВидРаботы CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ВидРаботы.Название CustomAttributes)

        // *** End programmer edit section *** (ВидРаботы.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ВидРаботы.Название Get start)

                // *** End programmer edit section *** (ВидРаботы.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ВидРаботы.Название Get end)

                // *** End programmer edit section *** (ВидРаботы.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВидРаботы.Название Set start)

                // *** End programmer edit section *** (ВидРаботы.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ВидРаботы.Название Set end)

                // *** End programmer edit section *** (ВидРаботы.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВидРаботыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидРаботыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидРаботыE", typeof(IIS.Vodokanal.ВидРаботы));
                }
            }
            
            /// <summary>
            /// "ВидРаботыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВидРаботыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВидРаботыL", typeof(IIS.Vodokanal.ВидРаботы));
                }
            }
        }
    }
}
