//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка.
    /// </summary>
    // *** Start programmer edit section *** (Заявка CustomAttributes)

    // *** End programmer edit section *** (Заявка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаE", new string[] {
            "Дата as \'Дата\'",
            "Адрес as \'Адрес\'"})]
    [View("ЗаявкаL", new string[] {
            "Дата as \'Дата\'",
            "Адрес as \'Адрес\'"})]
    public class Заявка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Заявка CustomMembers)

        // *** End programmer edit section *** (Заявка CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Дата CustomAttributes)

        // *** End programmer edit section *** (Заявка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Дата Get start)

                // *** End programmer edit section *** (Заявка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заявка.Дата Get end)

                // *** End programmer edit section *** (Заявка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Дата Set start)

                // *** End programmer edit section *** (Заявка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заявка.Дата Set end)

                // *** End programmer edit section *** (Заявка.Дата Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Заявка.Адрес CustomAttributes)

        // *** End programmer edit section *** (Заявка.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Заявка.Адрес Get start)

                // *** End programmer edit section *** (Заявка.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Заявка.Адрес Get end)

                // *** End programmer edit section *** (Заявка.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявка.Адрес Set start)

                // *** End programmer edit section *** (Заявка.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Заявка.Адрес Set end)

                // *** End programmer edit section *** (Заявка.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаE", typeof(IIS.Vodokanal.Заявка));
                }
            }
            
            /// <summary>
            /// "ЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаL", typeof(IIS.Vodokanal.Заявка));
                }
            }
        }
    }
}
