//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Работа.
    /// </summary>
    // *** Start programmer edit section *** (Работа CustomAttributes)

    // *** End programmer edit section *** (Работа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РаботаE", new string[] {
            "План as \'План\'",
            "Факт as \'Факт\'",
            "Заявка as \'Заявка\'",
            "Заявка.Адрес as \'Адрес\'",
            "ВидРаботы as \'Вид работы\'",
            "ВидРаботы.Название as \'Название\'"}, Hidden=new string[] {
            "Заявка.Адрес",
            "ВидРаботы.Название"})]
    [MasterViewDefineAttribute("РаботаE", "Заявка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("РаботаE", "ВидРаботы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [View("РаботаL", new string[] {
            "План as \'План\'",
            "Факт as \'Факт\'",
            "Заявка.Адрес as \'Адрес\'",
            "ВидРаботы.Название as \'Название\'"})]
    public class Работа : ICSSoft.STORMNET.DataObject
    {
        
        private int fПлан;
        
        private int fФакт;
        
        private IIS.Vodokanal.ВидРаботы fВидРаботы;
        
        private IIS.Vodokanal.Заявка fЗаявка;
        
        // *** Start programmer edit section *** (Работа CustomMembers)

        // *** End programmer edit section *** (Работа CustomMembers)

        
        /// <summary>
        /// План.
        /// </summary>
        // *** Start programmer edit section *** (Работа.План CustomAttributes)

        // *** End programmer edit section *** (Работа.План CustomAttributes)
        public virtual int План
        {
            get
            {
                // *** Start programmer edit section *** (Работа.План Get start)

                // *** End programmer edit section *** (Работа.План Get start)
                int result = this.fПлан;
                // *** Start programmer edit section *** (Работа.План Get end)

                // *** End programmer edit section *** (Работа.План Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Работа.План Set start)

                // *** End programmer edit section *** (Работа.План Set start)
                this.fПлан = value;
                // *** Start programmer edit section *** (Работа.План Set end)

                // *** End programmer edit section *** (Работа.План Set end)
            }
        }
        
        /// <summary>
        /// Факт.
        /// </summary>
        // *** Start programmer edit section *** (Работа.Факт CustomAttributes)

        // *** End programmer edit section *** (Работа.Факт CustomAttributes)
        public virtual int Факт
        {
            get
            {
                // *** Start programmer edit section *** (Работа.Факт Get start)

                // *** End programmer edit section *** (Работа.Факт Get start)
                int result = this.fФакт;
                // *** Start programmer edit section *** (Работа.Факт Get end)

                // *** End programmer edit section *** (Работа.Факт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Работа.Факт Set start)

                // *** End programmer edit section *** (Работа.Факт Set start)
                this.fФакт = value;
                // *** Start programmer edit section *** (Работа.Факт Set end)

                // *** End programmer edit section *** (Работа.Факт Set end)
            }
        }
        
        /// <summary>
        /// Работа.
        /// </summary>
        // *** Start programmer edit section *** (Работа.ВидРаботы CustomAttributes)

        // *** End programmer edit section *** (Работа.ВидРаботы CustomAttributes)
        [NotNull()]
        public virtual IIS.Vodokanal.ВидРаботы ВидРаботы
        {
            get
            {
                // *** Start programmer edit section *** (Работа.ВидРаботы Get start)

                // *** End programmer edit section *** (Работа.ВидРаботы Get start)
                IIS.Vodokanal.ВидРаботы result = this.fВидРаботы;
                // *** Start programmer edit section *** (Работа.ВидРаботы Get end)

                // *** End programmer edit section *** (Работа.ВидРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Работа.ВидРаботы Set start)

                // *** End programmer edit section *** (Работа.ВидРаботы Set start)
                this.fВидРаботы = value;
                // *** Start programmer edit section *** (Работа.ВидРаботы Set end)

                // *** End programmer edit section *** (Работа.ВидРаботы Set end)
            }
        }
        
        /// <summary>
        /// Работа.
        /// </summary>
        // *** Start programmer edit section *** (Работа.Заявка CustomAttributes)

        // *** End programmer edit section *** (Работа.Заявка CustomAttributes)
        [NotNull()]
        public virtual IIS.Vodokanal.Заявка Заявка
        {
            get
            {
                // *** Start programmer edit section *** (Работа.Заявка Get start)

                // *** End programmer edit section *** (Работа.Заявка Get start)
                IIS.Vodokanal.Заявка result = this.fЗаявка;
                // *** Start programmer edit section *** (Работа.Заявка Get end)

                // *** End programmer edit section *** (Работа.Заявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Работа.Заявка Set start)

                // *** End programmer edit section *** (Работа.Заявка Set start)
                this.fЗаявка = value;
                // *** Start programmer edit section *** (Работа.Заявка Set end)

                // *** End programmer edit section *** (Работа.Заявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РаботаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаботаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаботаE", typeof(IIS.Vodokanal.Работа));
                }
            }
            
            /// <summary>
            /// "РаботаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РаботаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РаботаL", typeof(IIS.Vodokanal.Работа));
                }
            }
        }
    }
}
